Repository dooboolab/wecount, pull requests merged in 2019-09, with the labels that each got.

#12 Implemented tutorial screen
  lib/main.dart
  lib/screens/find_pw.dart
  lib/screens/home_calendar.dart
  lib/screens/home_list.dart
  lib/screens/home_setting.dart
  lib/screens/home_statistic.dart
  lib/screens/intro.dart
  lib/screens/ledger_add.dart
  lib/screens/ledgers.dart
  lib/screens/login.dart
  lib/screens/profile_my.dart
  lib/screens/setting.dart
  lib/screens/setting_announcement.dart
  lib/screens/setting_faq.dart
  lib/screens/setting_notification.dart
  lib/screens/setting_opinion.dart
  lib/screens/sign_up.dart
  lib/screens/tutorial.dart
  lib/shared/button.dart
  lib/shared/dialog_spinner.dart
  lib/shared/edit_text.dart
  lib/shared/edit_text_box.dart
  lib/shared/edit_text_search.dart
  lib/shared/header.dart
  lib/shared/home_header.dart
  lib/shared/home_header_search.dart
  lib/shared/ledger_list_item.dart
  lib/shared/profile_image_cam.dart
  lib/shared/profile_list_item.dart
  lib/shared/setting_list_item.dart
  lib/utils/asset.dart
  lib/utils/general.dart
  res/icons/2.0x/tutorial1.png
  res/icons/2.0x/tutorial2.png
  res/icons/2.0x/tutorial3.png
  res/icons/3.0x/tutorial1.png
  res/icons/3.0x/tutorial2.png
  res/icons/3.0x/tutorial3.png
  res/icons/tutorial1.png
  res/icons/tutorial2.png
  res/icons/tutorial3.png
  res/langs/en.json
  res/langs/ko.json
  test/screens/find_pw_test.dart
  test/screens/intro_test.dart
  test/screens/login_test.dart
  test/screens/main_test.dart
  test/screens/sign_up_test.dart
  test/screens/splash_test.dart
  test/screens/tutorial_test.dart
  test/shared/button_test.dart
Labels: feature

#13 Update textTheme color
  lib/main.dart
  lib/screens/find_pw.dart
  lib/screens/home_calendar.dart
  lib/screens/setting_opinion.dart
  lib/screens/sign_up.dart
  lib/shared/edit_text.dart
  lib/shared/home_header.dart
Labels: config, enhancement

#15 Implement [MainEmpty] screen with test
  lib/main.dart
  lib/screens/main_empty.dart
  lib/screens/splash.dart
  lib/shared/button.dart
  lib/utils/asset.dart
  res/icons/2.0x/noLedger.png
  res/icons/3.0x/noLedger.png
  res/icons/noLedger.png
  res/langs/en.json
  res/langs/ko.json
  test/screens/main_empty_test.dart
  test/test_utils.dart
Labels: feature

#16 Fix minor ui
  lib/screens/home_calendar.dart
  lib/screens/ledgers.dart
  lib/screens/setting_opinion.dart
  lib/shared/home_header.dart
Labels: enhancement

#17 Change login icons according to brand guidelines
  lib/screens/intro.dart
  lib/utils/asset.dart
  res/icons/icFacebookB.png
  res/icons/icGoogleB.png
Labels: enhancement

#19 Enh/models ui
  .gitignore
  ios/Runner.xcodeproj/project.pbxproj
  lib/models/User.dart
  lib/screens/intro.dart
  lib/shared/button.dart
  lib/utils/asset.dart
  res/icons/2.0x/icFacebook.png
  res/icons/2.0x/icFacebookW.png
  res/icons/2.0x/icGoogle.png
  res/icons/2.0x/icGoogleW.png
  res/icons/3.0x/icFacebook.png
  res/icons/3.0x/icFacebookW.png
  res/icons/3.0x/icGoogle.png
  res/icons/3.0x/icGoogleW.png
  res/icons/icFacebook.png
  res/icons/icFacebookB.png
  res/icons/icFacebookW.png
  res/icons/icGoogle.png
  res/icons/icGoogleW.png
Labels: enhancement

#20 screen/ledger_item_add
  .gitignore
  lib/main.dart
  lib/models/LedgerItem.dart
  lib/models/Photo.dart
  lib/screens/find_pw.dart
  lib/screens/home_calendar.dart
  lib/screens/home_list.dart
  lib/screens/home_setting.dart
  lib/screens/home_statistic.dart
  lib/screens/ledger_item_add.dart
  lib/screens/ledgers.dart
  lib/screens/login.dart
  lib/screens/photo_detail.dart
  lib/screens/profile_my.dart
  lib/screens/sign_up.dart
  lib/shared/carousel.dart
  lib/shared/gallery.dart
  lib/shared/header.dart
  lib/utils/asset.dart
  lib/utils/general.dart
  pubspec.lock
  pubspec.yaml
  res/icons/2.0x/boxAdd.png
  res/icons/2.0x/icCoins.png
  res/icons/3.0x/boxAdd.png
  res/icons/3.0x/icCoins.png
  res/icons/boxAdd.png
  res/icons/icCoins.png
  res/langs/en.json
  res/langs/ko.json
Labels: feature, screen

#22 Feat/category
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/ko.lproj/LaunchScreen.strings
  ios/Runner/ko.lproj/Main.strings
  lib/main.dart
  lib/models/Category.dart
  lib/navigations/home_tab.dart
  lib/screens/category_add.dart
  lib/screens/find_pw.dart
  lib/screens/home_calendar.dart
  lib/screens/home_list.dart
  lib/screens/home_setting.dart
  lib/screens/home_statistic.dart
  lib/screens/intro.dart
  lib/screens/ledger_add.dart
  lib/screens/ledger_item_add.dart
  lib/screens/ledgers.dart
  lib/screens/login.dart
  lib/screens/main_empty.dart
  lib/screens/photo_detail.dart
  lib/screens/profile_my.dart
  lib/screens/setting.dart
  lib/screens/setting_announcement.dart
  lib/screens/setting_faq.dart
  lib/screens/setting_notification.dart
  lib/screens/setting_opinion.dart
  lib/screens/sign_up.dart
  lib/screens/splash.dart
  lib/screens/tutorial.dart
  lib/shared/carousel.dart
  lib/shared/category_item.dart
  lib/shared/category_list.dart
  lib/shared/edit_text_box.dart
  lib/shared/gallery.dart
  lib/shared/header.dart
  lib/shared/home_header.dart
  lib/shared/home_header_search.dart
  lib/shared/ledger_list_item.dart
  lib/shared/profile_image_cam.dart
  lib/shared/profile_list_item.dart
  lib/shared/setting_list_item.dart
  lib/utils/asset.dart
  lib/utils/db_helper.dart
  lib/utils/general.dart
  pubspec.yaml
  res/langs/en.json
  res/langs/ko.json
  test/screens/category_add_test.dart
  test/screens/ledger_item.add_test.dart
  test/shared/category_item_test.dart
  test/shared/category_list_test.dart
Labels: enhancement, feature

#21 Implement HOME_SETTING
  lib/main.dart
  lib/screens/home_setting.dart
  lib/screens/setting_currency.dart
  lib/screens/setting_excel.dart
  lib/shared/setting_list_item.dart
  res/langs/en.json
  res/langs/ko.json
  test/screens/home_setting_test.dart
  test/screens/setting_currency_test.dart
  test/screens/setting_excel_test.dart
Labels: feature, screen

#23 Configure google places and geolocation
  README.md
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/models/LedgerItem.dart
  lib/screens/ledger_item_add.dart
  lib/screens/location_view.dart
  lib/screens/map_address.dart
  lib/shared/gallery.dart
  lib/utils/localization.dart
  lib/utils/service.dart
  pubspec.yaml
  test/screens/location_view_test.dart
Labels: enhancement, feature

#27 Make [LedgerAdd] ready to sumit data to server
  ios/Podfile.lock
  lib/main.dart
  lib/models/Currency.dart
  lib/models/Ledger.dart
  lib/screens/ledger_add.dart
  lib/screens/ledger_item_add.dart
  lib/screens/setting_currency.dart
Labels: enhancement
