Repository dooboolab/wecount, pull requests merged in 2022-06, with the labels that each got.

#54 [WIP] Ledger CRUD implmentation enhancement
  .env.sample
  android/app/build.gradle
  lib/models/Ledger.dart
  lib/navigations/auth_switch.dart
  lib/screens/ledger_edit.dart
  lib/services/database.dart
  res/langs/en.json
  res/langs/ko.json
Labels: enhancement

#55 migration: flutter v3 and update flutter packages to recent
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
  lib/main.dart
  lib/models/Ledger.dart
  lib/models/LedgerItem.dart
  lib/models/Photo.dart
  lib/navigations/auth_switch.dart
  lib/navigations/home_tab.dart
  lib/screens/home_calendar.dart
  lib/screens/home_statistic/home_statistic.dart
  lib/screens/intro.dart
  lib/screens/ledger_item_edit.dart
  lib/screens/ledgers.dart
  lib/screens/line_graph.dart
  lib/screens/location_view.dart
  lib/screens/lock_auth.dart
  lib/screens/photo_detail.dart
  lib/screens/profile_my.dart
  lib/screens/sign_in.dart
  lib/screens/sign_up.dart
  lib/services/database.dart
  lib/services/storage.dart
  lib/shared/carousel.dart
  lib/shared/gallery.dart
  lib/shared/line_graph_chart.dart
  lib/shared/profile_image_cam.dart
  lib/utils/general.dart
  lib/utils/service.dart
  pubspec.yaml
Labels: 🚽 migration

#58 Enhance translations
  lib/generated/intl/messages_all.dart
  lib/generated/intl/messages_en.dart
  lib/generated/intl/messages_ko.dart
  lib/generated/l10n.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_ko.arb
  lib/main.dart
  lib/mocks/home_calendar.mock.dart
  lib/mocks/home_statistic.mock.dart
  lib/mocks/line_graph.mock.dart
  lib/models/category.dart
  lib/navigations/auth_switch.dart
  lib/screens/category_add.dart
  lib/screens/find_pw.dart
  lib/screens/home_calendar.dart
  lib/screens/home_list.dart
  lib/screens/home_setting.dart
  lib/screens/home_statistic/home_statistic.dart
  lib/screens/intro.dart
  lib/screens/ledger_edit.dart
  lib/screens/ledger_item_edit.dart
  lib/screens/ledger_view.dart
  lib/screens/ledgers.dart
  lib/screens/line_graph.dart
  lib/screens/lock_auth.dart
  lib/screens/lock_register.dart
  lib/screens/main_empty.dart
  lib/screens/members.dart
  lib/screens/photo_detail.dart
  lib/screens/profile_my.dart
  lib/screens/profile_peer.dart
  lib/screens/setting.dart
  lib/screens/setting_announcement.dart
  lib/screens/setting_currency.dart
  lib/screens/setting_excel.dart
  lib/screens/setting_faq.dart
  lib/screens/setting_notification.dart
  lib/screens/setting_opinion.dart
  lib/screens/sign_in.dart
  lib/screens/sign_up.dart
  lib/screens/tutorial.dart
  lib/shared/button.dart
  lib/shared/category_list.dart
  lib/shared/gallery.dart
  lib/shared/header.dart
  lib/shared/home_header_search.dart
  lib/shared/ledger_list_item.dart
  lib/shared/member_horizontal_list.dart
  lib/shared/member_list_item.dart
  lib/utils/constants.dart
  lib/utils/general.dart
  lib/utils/localization.dart
  lib/utils/service.dart
  pubspec.yaml
  test/screens/main_test.dart
  test/test_utils.dart
Labels: 🇰🇷 translation

#59 Improve project usage
  .env.sample
  .firebaserc
  README.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  firebase.json
  functions/.eslintignore
  functions/.gitignore
  functions/.prettierrc.cjs
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/src/seeds/index.ts
  functions/src/seeds/user.ts
  functions/src/utils/auth.ts
  functions/src/utils/functions.ts
  functions/tsconfig.json
  functions/yarn.lock
  lib/generated/intl/messages_en.dart
  lib/generated/intl/messages_ko.dart
  lib/generated/l10n.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_ko.arb
  lib/main.dart
  lib/screens/category_add.dart
  lib/screens/empty.dart
  lib/screens/home_calendar.dart
  lib/screens/home_list.dart
  lib/screens/home_setting.dart
  lib/screens/home_statistic/home_statistic.dart
  lib/screens/intro.dart
  lib/screens/ledger_edit.dart
  lib/screens/ledger_item_edit.dart
  lib/screens/ledger_view.dart
  lib/screens/ledgers.dart
  lib/screens/main_empty.dart
  lib/screens/members.dart
  lib/screens/setting.dart
  lib/screens/setting_announcement.dart
  lib/screens/setting_excel.dart
  lib/screens/setting_faq.dart
  lib/screens/setting_notification.dart
  lib/screens/setting_opinion.dart
  lib/screens/sign_up.dart
  lib/screens/tutorial.dart
  lib/shared/edit_text_box.dart
  lib/shared/gallery.dart
  lib/shared/header.dart
  lib/shared/home_header.dart
  lib/shared/home_list_item.dart
  lib/shared/ledger_list_item.dart
  lib/shared/member_horizontal_list.dart
  lib/utils/asset.dart
  lib/utils/colors.dart
  lib/utils/firebase_config.dart
  lib/utils/themes.dart
  pubspec.yaml
  res/langs/en.json
  res/langs/ko.json
Labels: 🍗 enhancement, 🎯 feature

#60 Improve Firebase usability
  .firebaserc
  README.md
  firebase/.firebaserc_example
  firebase/.gitignore
  firebase/.vscode/extensions.json
  firebase/.vscode/settings.json
  firebase/README.md
  firebase/doc/database_url.png
  firebase/doc/private_key.png
  firebase/firebase.json
  firebase/firestore.indexes.json
  firebase/firestore.rules
  firebase/functions/.env_example
  firebase/functions/.eslintignore
  firebase/functions/.eslintrc.js
  firebase/functions/.gitignore
  firebase/functions/.prettierrc.cjs
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/src/index.ts
  firebase/functions/src/seeds/index.ts
  firebase/functions/src/seeds/user.ts
  firebase/functions/src/utils/auth.ts
  firebase/functions/src/utils/functions.ts
  firebase/functions/tsconfig.dev.json
  firebase/functions/tsconfig.json
  firebase/functions/yarn.lock
  firebase/storage.rules
  functions/.gitignore
  functions/src/index.ts
  functions/tslint.json
  functions/yarn.lock
  lib/utils/db_helper.dart
Labels: 🍗 enhancement
